### ISSUE TITLE
App tries to download branding 'null'

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/mobicage-android-client#127]
Happens after receiving welcome message flow. The branding of the message was `null`.

```
04-25 14:46:18.211  5741  5867 D MC      : ???? | Downloading branding: https://rogerth.at/unauthenticated/mobi/branding/null
04-25 14:46:18.458  5741  5867 D MC      : ???? | Failed to download branding file null for service 'dashboard@rogerth.at' and start flow hash: c115930aa77d5d52dc03f16d0b60899e
04-25 14:46:18.458  5741  5867 D MC      : java.lang.Exception: Received unexpected statusCode: 404
04-25 14:46:18.458  5741  5867 D MC      : 	at com.mobicage.rogerthat.plugins.messaging.BrandingMgr$10.download(BrandingMgr.java:1957)
04-25 14:46:18.458  5741  5867 D MC      : 	at com.mobicage.rogerthat.plugins.messaging.BrandingMgr$10.safeRun(BrandingMgr.java:2057)
04-25 14:46:18.458  5741  5867 D MC      : 	at com.mobicage.rogerthat.util.system.SafeRunnable.run(SafeRunnable.java:52)
04-25 14:46:18.458  5741  5867 D MC      : 	at android.os.Handler.handleCallback(Handler.java:751)
04-25 14:46:18.458  5741  5867 D MC      : 	at android.os.Handler.dispatchMessage(Handler.java:95)
04-25 14:46:18.458  5741  5867 D MC      : 	at android.os.Looper.loop(Looper.java:154)
04-25 14:46:18.458  5741  5867 D MC      : 	at android.os.HandlerThread.run(HandlerThread.java:61)

```

**Comment by bart-at-mobicage** [comment]
server-side issue: `"brandings_to_dwnl":["null"]`

**Comment by lucasvanhalst** [comment]
Fixed on the server, is this still relevant then?
