### ISSUE TITLE
Back button closes app 

### ISSUE THREAD

**Issue by RubenMattan** [our-city-app/mobicage-android-client#223]
On my phone (not sure if other users experience this) the back button on most pages exits the app (instead of going to the previous window) after the screen was locked and unlocked again.

- reported app SHaRE (style: homescreen)

**Comment by lucasvanhalst** [comment]
can you give exact examples? works fine for me in the aalter app

**Comment by RubenMattan** [comment]
Open the share app
- click on messages
- lock your screen
- press the back button
-> app closes

**Comment by lucasvanhalst** [comment]
```

2020-10-14 09:36:34.114 1061-10514/? W/ActivityManager: Exception when unbinding service com.mobicage.rogerthat.za.stellenbosch/org.chromium.content.app.SandboxedProcessService0:4
    android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(BinderProxy.java:575)
        at android.app.IApplicationThread$Stub$Proxy.scheduleUnbindService(IApplicationThread.java:1759)
        at com.android.server.am.ActiveServices.removeConnectionLocked(ActiveServices.java:3424)
        at com.android.server.am.ActiveServices.unbindServiceLocked(ActiveServices.java:2087)
        at com.android.server.am.ActivityManagerService.unbindService(ActivityManagerService.java:17021)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2733)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3427)
        at android.os.Binder.execTransactInternal(Binder.java:1056)
        at android.os.Binder.execTransact(Binder.java:1029)
2020-10-14 09:36:34.120 1061-10514/? I/ActivityManager: Killing 27784:com.google.android.webview:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:4/u0a430i48 (adj 905): isolated not needed
```
this happens when you lock the screen

**Comment by lucasvanhalst** [comment]
looks like this no longer happens on the home screen branch so I'm not gonna fix it
