### ISSUE TITLE
Unable to create notifications on android  8+

### ISSUE THREAD

**Issue by RubenMattan** [our-city-app/mobicage-android-client#63]
```java

09-07 09:55:40.474  8239  8239 E MC      : ???? | Uncaught exception
09-07 09:55:40.474  8239  8239 E MC      : java.lang.RuntimeException: Unable to start receiver com.mobicage.rogerthat.GCMReveiver: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.mobicage.rogerth.at/com.mobicage.rogerthat.MainService (has extras) }: app is in background uid UidRecord{830b8f8 u0a97 RCVR idle procs:1 seq(0,0,0)}
09-07 09:55:40.474  8239  8239 E MC      : 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3259)
09-07 09:55:40.474  8239  8239 E MC      : 	at android.app.ActivityThread.-wrap17(Unknown Source:0)
09-07 09:55:40.474  8239  8239 E MC      : 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677)
09-07 09:55:40.474  8239  8239 E MC      : 	at android.os.Handler.dispatchMessage(Handler.java:105)
09-07 09:55:40.474  8239  8239 E MC      : 	at android.os.Looper.loop(Looper.java:164)
09-07 09:55:40.474  8239  8239 E MC      : 	at android.app.ActivityThread.main(ActivityThread.java:6541)
09-07 09:55:40.474  8239  8239 E MC      : 	at java.lang.reflect.Method.invoke(Native Method)
09-07 09:55:40.474  8239  8239 E MC      : 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
09-07 09:55:40.474  8239  8239 E MC      : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
09-07 09:55:40.474  8239  8239 E MC      : Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.mobicage.rogerth.at/com.mobicage.rogerthat.MainService (has extras) }: app is in background uid UidRecord{830b8f8 u0a97 RCVR idle procs:1 seq(0,0,0)}
09-07 09:55:40.474  8239  8239 E MC      : 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1505)
09-07 09:55:40.474  8239  8239 E MC      : 	at android.app.ContextImpl.startService(ContextImpl.java:1461)
09-07 09:55:40.474  8239  8239 E MC      : 	at android.content.ContextWrapper.startService(ContextWrapper.java:644)
09-07 09:55:40.474  8239  8239 E MC      : 	at android.content.ContextWrapper.startService(ContextWrapper.java:644)
09-07 09:55:40.474  8239  8239 E MC      : 	at android.support.v4.content.WakefulBroadcastReceiver.startWakefulService(WakefulBroadcastReceiver.java:99)
09-07 09:55:40.474  8239  8239 E MC      : 	at com.mobicage.rogerthat.GCMReveiver.onReceive(GCMReveiver.java:32)
09-07 09:55:40.474  8239  8239 E MC      : 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3252)
09-07 09:55:40.474  8239  8239 E MC      : 	... 8 more

```

**Comment by RubenMattan** [comment]
Created a pull request https://github.com/our-city-app/mobicage-android-client/pull/64, still needs some more testing

**Comment by lucasvanhalst** [comment]
play store is going to reject the updates in a few months https://github.com/our-city-app/mobicage-android-client/issues/4

From August 2018, new apps must target at least Android 8.0 (API level 26).
From November 2018, app updates must target Android 8.0 (API level 26).

**Comment by RubenMattan** [comment]
see https://developer.android.com/distribute/best-practices/develop/target-sdk
