### ISSUE TITLE
Invalid V8 thread access

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/mobicage-android-client#92]
```
description: Uncaught exception

errorMessage: java.lang.Error: Invalid V8 thread access: current thread is Thread[rogerthat_http_worker,5,main] while the locker has thread Thread[rogerthat_http_worker,5,]
	at com.eclipsesource.v8.V8Locker.checkThread(V8Locker.java:99)
	at com.eclipsesource.v8.V8.checkThread(V8.java:771)
	at com.eclipsesource.v8.V8.executeScript(V8.java:666)
	at com.eclipsesource.v8.V8.executeScript(V8.java:651)
	at com.mobicage.rogerthat.plugins.messaging.mfr.JsMfr$1.safeRun(JsMfr.java:187)
	at com.mobicage.rogerthat.util.system.SafeRunnable.run(SafeRunnable.java:52)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.os.HandlerThread.run(HandlerThread.java:61)


mobicageVersion: 2.1.4637.A

occurenceCount: 1

platform: 1

platformVersion: 24
```

**Comment by lucasvanhalst** [comment]
This happens because the Thread that handles the v8 instance has been killed 

See toString of java.lang.Thread:
```java
    public String toString() {
        ThreadGroup group = getThreadGroup();
        if (group != null) {
            return "Thread[" + getName() + "," + getPriority() + "," +
                           group.getName() + "]";
        } else {
            return "Thread[" + getName() + "," + getPriority() + "," +
                            "" + "]";
        }
    }
```

and getThreadGroup only returns null in case the thread has been terminated:

```java
    public final ThreadGroup getThreadGroup() {
        // Android-changed: Return null if the thread is terminated.
        if (getState() == Thread.State.TERMINATED) {
            return null;
        }
        return group;
    }
```

So I don't think we can fix this ?
